# Generated by Django 3.1.4 on 2020-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uploaded', models.FileField(upload_to='')),
                ('public_ip', models.GenericIPAddressField(default='127.0.0.1', null=True)),
                ('name', models.CharField(max_length=200)),
                ('paper_code', models.IntegerField()),
                ('total_marks', models.FloatField()),
                ('engcount', models.FloatField()),
                ('ctcount', models.FloatField()),
                ('statcount', models.FloatField()),
                ('mathcount', models.FloatField()),
            ],
        ),
    ]
